name: Generate Pac-Man (Monthly Contributions)

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the first day of every month at midnight
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man GIF
        uses: Platane/snk@master
        with:
          github_user_name: Tanishq6150
          gif_out_path: dist/github-contribution-grid-pacman.gif
          svg_out_path: dist/github-contribution-grid-pacman.svg
          mode: pacman  # Enables Pac-Man animation

      - name: Show Git Status
        run: git status

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
